import type { Metadata } from "next";
import { Inter, Open_Sans, Poppins } from "next/font/google";
import "./styles/globals.css";
import { inter } from "@/shared/fonts/fonts";
import { Provider } from "react-redux";
// import { store } from "./model/store";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="ru">
        <body className={inter.variable}>{children}</body>
      </html>
    </StoreProvider>
  );
}
